services:
  - type: web
    name: healthcare-dashboard
    env: node
    plan: starter
    region: oregon
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
    autoDeploy: true
    branch: master
